# 1. How to check if a string contains only numbers in Python

### Method 1 :  str.isdecimal()          supports only Decimal Numbers

In [1]:
print("1234".isdecimal())

True


In [7]:
print("0123456789".isdecimal())

True


In [2]:
print("a1234".isdecimal())

False


In [3]:
print("-123".decimal())

AttributeError: 'str' object has no attribute 'decimal'

### Method 2 : str.isdigit()  supports Decimals, Subscripts, Superscripts

In [8]:
print("1234".isdigit())

True


In [9]:
print("a1234".isdigit())

False


### Method 3 : str.isnumeric()  supports Digits, Vulgar Fractions, Subscripts, Superscripts, Roman Numerals, Currency Numerators

In [10]:
print("1234".isnumeric())

True


In [11]:
print("-1234".isnumeric())

False


### Method 4 : regex

In [19]:
import re

strings = input("Enter the Numeric string: ")
print(type(strings))
if re.match('^[0-9]*$', strings):
    print(string,"is a numeric string")
else:
    print(string,"is not a numeric string")

Enter the Numeric string: 1234
<class 'str'>
123 is a numeric string


# 2. How to find duplicate characters in a String? 

In [17]:
string = input("Enter the string: ")

for i in range(0,len(string)):
    count = 1
    for j in range(i+1,len(string)):
        if (string[i] == string[j] and string[i]!=''):
            count = count + 1
            string = string[:j] + '0' + string[j+1:] 
            
    if (count>1 and string[i]!='0'):
        print(string[i])

Enter the string: Aiswariya
i
a


# 3. How to count a number of vowels and consonants in a given String?

In [18]:
string = input("Enter the string: ")

vowels=0
consonants=0

for i in string:
    if (i=='A' or i=='E' or i=='I' or i=='O' or i=='U'
       or i=='a' or i=='e' or i=='i' or i=='o' or i=='u'):
        vowels=vowels+1
    else:
        consonants=consonants+1
        
print("The number of consonants are:",consonants) 
print("The number of vowels are:",vowels) 

Enter the string: Alphabets
The number of consonants are: 6
The number of vowels are: 3


# 4. How to count the occurrence of a given character in String? 

In [27]:
str = input("Enter the string: ")
i = input("Enter the character: ")

x=str.lower()
count = x.count(i)

print("The occurence of ",i," in ",str,":",count)

Enter the string: ANN
Enter the character: n
The occurence of  n  in  ANN : 2


In [28]:
str = input("Enter the string: ")
i = input("Enter the character: ")

import re
count=len(re.findall(i,str))

print("The occurence of ",i," in ",str,":",count)

Enter the string: ANN
Enter the character: N
The occurence of  N  in  ANN : 2


# 5.	How to find all permutations of String? 

In [5]:
from itertools import permutations

x=input("Enter the string:")
permutation = [''.join(p) for p in permutations(x)]
print("Permuation of the string",x,': \t',str(permutation))

Enter the string:HAT
Permuation of the string HAT : 	 ['HAT', 'HTA', 'AHT', 'ATH', 'THA', 'TAH']


# 6.	How to find & count any given pattern from a text?
e.g. ‘EDUCATION’, find number of ‘CAT' occurrence in the text?


In [6]:
text = "EDUCATION"
print("The number of occurrence of CAT in",text,"is: ",text.find("CAT"))

The number of occurrence of CAT in EDUCATION is:  3


# 7.	How to remove duplicates from an array in place?

### Method 1 : Using For loop

In [45]:
list = [1,1,1,2,3,3,4,5,5,6,6]
final_list = []
for i in list:
    if i not in final_list:
        final_list.append(i)        
print(final_list)

[1, 2, 3, 4, 5, 6]


### Method 2 : Using Numpy

In [43]:
import numpy as np
list = [1,1,1,2,3,3,4,5,5,6,6]
final_list = np.unique(list).tolist()
print(final_list)

[1, 2, 3, 4, 5, 6]


### Method 3 : Using Pandas

In [42]:
import pandas as pd
list = [1,1,1,2,3,3,4,5,5,6,6]
final_list = pd.unique(list).tolist()
print(final_list)

[1, 2, 3, 4, 5, 6]


### Method 4 : Using Set

In [46]:
list = [1,1,1,2,3,3,4,5,5,6,6]
final_list = set(list)
print(final_list)

{1, 2, 3, 4, 5, 6}


# 8.	How to reverse a String?

In [29]:
str = input("Enter the string: ")
print(str[::-1])

Enter the string: Aiswarya
ayrawsiA


In [30]:
str = input("Enter the string: ")
print("".join(reversed(str)))

Enter the string: Aiswarya
ayrawsiA


# 9.	How to find the highest repeating word from a given file?

In [41]:
file=open("Peter.txt")
freq_word=""
frequency=0
words=[]

for line in file:
    line_word=line.lower().replace(',','').replace('.','').replace('?','').split(" ")
    for x in line_word:
        words.append(x)

for i in range(0,len(words)):
    count=1
    for j in range(i+1,len(words)):
        if(words[i]==words[j]):
            count=count+1
            
    if count>frequency :
        frequency=count
        freq_word=words[i]
        
print("Highest repeated word: " + freq_word)
print("Frequency",frequency)
file.close()

Highest repeated word: peter
Frequency 4


# 10.	How to check if the given number is a prime number?

In [49]:
n = int(input("Enter the number:"))

if n%2 != 0:
    print(n,"is a prime number")
else:
    print(n,"is not a prime number")

Enter the number:23
23 is a prime number


In [52]:
n = int(input("Enter the number:"))

if n>1 :
    
    for i in range(2, int(n/2)+1):
        if n%i == 0:
            print(n, "not a prime")
            break
    else:
        print(n, "is prime")      
else:
    print(n,"is not a prime number")

Enter the number:11
11 is prime


# 11.	How do you find all prime factors of a given number?

In [10]:
Number = int(input("Enter the Number: "))

i = 1

while(i <= Number):
    count = 0
    if(Number % i == 0):
        j = 1
        while(j <= i):
            if(i % j == 0):
                count = count + 1
            j = j + 1
            
        if (count == 2):
            print(" %d is a Prime Factor of a Given Number %d" %(i, Number))
    i = i + 1

Enter the Number: 10
 2 is a Prime Factor of a Given Number 10
 5 is a Prime Factor of a Given Number 10


# 12.	Write a Program to transpose a Matrix?

In [57]:
x=[[1,2],[4,6],[8,9]]
result=[[0,0,0],[0,0,0]]

for i in range(len(x)):
    for j in range(len(x[0])):
        result[j][i] = x[i][j]    
        
print(result)   

[[1, 4, 8], [2, 6, 9]]


# 13.	Write a Program to add or subtract two Matrices?

In [68]:
import numpy as np

x1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
x2 = np.array([[11,12,13],[14,15,16],[17,18,19]])

print(np.add(x1,x2))
print(np.subtract(x2,x1))

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]


# 14.	How to implement the Bubble Sort algorithm?

In [62]:
list = [21,6,9,33,3]

n=len(list)
 
for i in range (n-1):
    for j in range(0,n-i-1):
        if list[j]>list[j+1]:
            temp=list[j+1]
            list[j+1]=list[j]
            list[j]=temp
            
print(list)            

[3, 6, 9, 21, 33]


# 15.	Find the words and its count for a given text file?

In [60]:
file=open("Peter.txt")
data=file.read()
words=data.split()

print("Number of words in a text file:",len(words))
print("Words in a text file: \n",words)

Number of words in a text file: 34
Words in a text file: 
 ['Peter', 'Piper', 'picked', 'a', 'peck', 'of', 'pickled', 'peppers', 'A', 'peck', 'of', 'pickled', 'peppers', 'Peter', 'Piper', 'picked', 'If', 'Peter', 'Piper', 'picked', 'a', 'peck', 'of', 'pickled', 'peppers', 'Where’s', 'the', 'peck', 'of', 'pickled', 'peppers', 'Peter', 'Piper', 'picked?']
